### ISSUE TITLE
python manage.py syncdb --noinput

### ISSUE THREAD

**Issue by nrchaudhry** [xflows/clowdflows#24]
Setting up python3-mysql.connector (2.1.6-1) ...
(mothra-env) nauman@nauman-VirtualBox:~/mothra-env/clowdflows$ python manage.py syncdb --noinput
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/home/nauman/mothra-env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/home/nauman/mothra-env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/nauman/mothra-env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 261, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/nauman/mothra-env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 69, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/home/nauman/mothra-env/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/nauman/mothra-env/local/lib/python2.7/site-packages/south/management/commands/__init__.py", line 10, in <module>
    import django.template.loaders.app_directories
  File "/home/nauman/mothra-env/local/lib/python2.7/site-packages/django/template/loaders/app_directories.py", line 23, in <module>
    raise ImproperlyConfigured('ImportError %s: %s' % (app, e.args[0]))
django.core.exceptions.ImproperlyConfigured: ImportError workflows.mysql: No module named mysql
(mothra-env) nauman@nauman-VirtualBox:~/mothra-env/clowdflows$

**Comment by janezkranjc** [comment]
Hey man, looks to me like you're using python3 - this version of clowflows works on python2
