### ISSUE TITLE
Update for Python 3?

### ISSUE THREAD

**Issue by brylie** [xflows/clowdflows#28]
With the Python 2 EoL looming, it is a good time to port this project to Python 3 (and Django 2).

E.g. when installing the project on Ubuntu 19.10, which has started using Python 3 as default, I get the following error:

```
$ pip install -r requirements.txt
...
ERROR: Command errored out with exit status 1:
     command: /home/brylie/Code/clowdflows/mothra-env/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-c1z23ilu/PySimpleSOAP/setup.py'"'"'; __file__='"'"'/tmp/pip-install-c1z23ilu/PySimpleSOAP/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-c1z23ilu/PySimpleSOAP/pip-egg-info
         cwd: /tmp/pip-install-c1z23ilu/PySimpleSOAP/
    Complete output (8 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-c1z23ilu/PySimpleSOAP/setup.py", line 10, in <module>
        import pysimplesoap.client
      File "/tmp/pip-install-c1z23ilu/PySimpleSOAP/pysimplesoap/client.py", line 206
        print "-"*80
                ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("-"*80)?
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

What are some of the major blockers in a Python 3 update?

**Comment by janezkranjc** [comment]
Hey man! A new version is in the works that uses Python 3 - check out these two repos:

https://github.com/xflows/clowdflows-backend
https://github.com/xflows/clowdflows-webapp
